# Generated by Django 5.2.7 on 2025-11-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='appointmentslot',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='appointmentslot',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
